### ISSUE TITLE
添加 `robots.txt` 可以让网站变得更容易被搜索引擎收录

### ISSUE THREAD

**Issue by Deycoesr** [ljl2107/hexoLBlog#4]
详情解释见 [robots.txt - Wikipedia](https://en.wikipedia.org/wiki/Robots.txt)

比如 [bilibili](https://www.bilibili.com/robots.txt) 的 robots.txt

```txt

User-agent: *
Disallow: /medialist/detail/
Disallow: /index.html

User-agent: Yisouspider
Allow: /

User-agent: Applebot
Allow: /

User-agent: bingbot
Allow: /

User-agent: Sogou inst spider
Allow: /

User-agent: Sogou web spider
Allow: /

User-agent: 360Spider
Allow: /

User-agent: Googlebot
Allow: /

User-agent: Baiduspider
Allow: /

User-agent: Bytespider
Allow: /

User-agent: PetalBot
Allow: /

User-agent: *
Disallow: /

```

**Comment by ljl2107** [comment]
谢谢！我在回家后会琢磨着把它弄上的，再次感谢（￣︶￣）↗

**Comment by Deycoesr** [comment]
已经在 [Google](https://www.google.com/search?q=site%3Aljl2107.top) 上看到效果了

![image](https://github.com/ljl2107/hexoLBlog/assets/33995808/584786c7-7ea5-43f0-bf98-aa3f6943b326)
